trigger:
  branches:
    include:
    - development
  paths:
    include:
    - '*'
    exclude:
    - 'README.md'
    - '**/*.yml'

variables: 
- group: connxio-docs-dev

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node 16.x'

- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: 'Disable SEO'
  inputs:
    targetFiles: '**/docusaurus.config.js'

- script: npm ci
  displayName: 'Install dependencies'
  workingDirectory: './site'

- script: npm run build
  displayName: 'Build website'
  workingDirectory: './site'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/site/build'
    includeRootFolder: false

- task: CopyFiles@2
  inputs:
    SourceFolder: './site/build'
    Contents: '*.zip'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'Copy build files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    appType: 'webApp'
