# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
